title: Mystika
description: tiny place

footer-links:
  dribbble:
  email:
  facebook:
  github: mystika
  rss: 
  twitter: BlurEffect

google_analytics: UA-66451315-1

url: http://mystika.me

baseurl: ""
permalink: none

paginate: 10

markdown: kramdown

kramdown:
    input: GFM